application: niffy-pixelscamp
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /_ah/(mapreduce|queue|warmup|start|stop).*
  script: niffy.wsgi.application
  login: admin
  secure: always

- url: /_ah/internalupload.*
  script: niffy.wsgi.application
  secure: always

- url: /(favicon\.ico|tile\.png|tile-wide\.png|robots.txt|humans\.txt|browserconfig\.xml)$
  static_files: static/\1
  upload: static/(favicon\.ico|tile\.png|tile-wide\.png|robots.txt|humans\.txt|browserconfig\.xml)$

- url: /static
  static_dir: static/
  secure: always

# Set Django admin to be login:admin as well as Django's is_staff restriction
- url: /admin.*
  script: niffy.wsgi.application
  secure: always
  login: admin

- url: /.*
  script: niffy.wsgi.application
  secure: always

skip_files:
    - manage.py
    - README.md
    - install_deps
    - requirements.txt
    - sitepackages/dev*
    - \.storage.*
    - \.git
    - (.*)\.pyc
